pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot pull requests
    conditions:
      - author=dependabot[bot]
      # condition
      # https://docs.mergify.com/conditions/#github-actions
      # 不一定全都会响应 在此判定 任意一个失败都不可以
      # 必须用 not or
      # 修改成这样是因为 无法匹配 matrix
      # https://github.com/Mergifyio/mergify/discussions/5067#discussioncomment-4859692
      - not:
          or:
            - check-failure~=^deploy-game
            - check-failure~=^deploy-art
            - check-failure~=^deploy-article
            - check-failure~=^deploy-code
            - check-failure~=^deploy-food
            - check-failure~=^deploy-notes
            - check-failure~=^deploy-trip
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - not:
          or:
            - check-failure~=^deploy-game
            - check-failure~=^deploy-art
            - check-failure~=^deploy-article
            - check-failure~=^deploy-code
            - check-failure~=^deploy-food
            - check-failure~=^deploy-notes
            - check-failure~=^deploy-trip
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - not:
          or:
            - check-failure~=^deploy-game
            - check-failure~=^deploy-art
            - check-failure~=^deploy-article
            - check-failure~=^deploy-code
            - check-failure~=^deploy-food
            - check-failure~=^deploy-notes
            - check-failure~=^deploy-trip
    actions:
      merge:
        method: merge

  # - name: automatic merge for auto pull requests
  #   conditions:
  #     - title=pulling refs/heads/dev into master
  #   actions:
  #     merge:
  #       method: merge
