pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - -check-failure~=^deploy-
      - -check-failure~=^py-
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - -check-failure~=^deploy-
      - -check-failure~=^py-
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - -check-failure~=^deploy-
      - -check-failure~=^py-
    actions:
      merge:
        method: merge

  - name: automatic merge for python script latest life
    conditions:
      - author=DrAugus
      - "title=docs: life latest"
      - -check-failure~=^deploy-
      - -check-failure~=^py-
    actions:
      merge:
        method: merge

  - name: automatic merge for auto get mhy wish
    conditions:
      - author=DrAugus
      - "title=feat: auto get mhy wish"
      - -check-failure~=^deploy-
      - -check-failure~=^py-
    actions:
      merge:
        method: merge
