pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot/Renovate/Requires.io pull requests
    conditions:
      - or:
        - and:
          - author=dependabot[bot]
        - and:
          - title~=^\[requires.io\]
          - head~=^requires-io      
        - and:
          - author=renovate[bot]              
      # PR is not a draft
      - -draft
      # condition
      # https://docs.mergify.com/conditions/#github-actions
      # 不一定全都会响应 在此判定 任意一个失败都不可以
      # 必须用 not or
      # 修改成这样是因为 无法匹配 matrix
      # https://github.com/Mergifyio/mergify/discussions/5067#discussioncomment-4859692
      # need to list every CI that you expect.
      # https://github.com/Mergifyio/mergify/discussions/5119
      # https://github.com/Mergifyio/mergify/discussions/5120
      - and:
        - or:
          - files~=^life/
          - files=".github/workflows/deploy-life.yml"
          - files=pnpm-lock.yaml
        - check-success=deploy-life (ubuntu-latest, 16, life/.vitepress/dist, augusmeow, life)
        - check-success=deploy-life (ubuntu-latest, 16, life/.vitepress/dist, augusmeow, augusmeow.github.io)
      - and:
        - or:
          - files~=^game/
          - files=".github/workflows/deploy-game.yml"
          - files=pnpm-lock.yaml
        - check-success=deploy-game (ubuntu-latest, 16, game/.vitepress/dist, augusmeow, game)    
      - and:
        - or:
          - files="script/requirements.txt"
          - files=".github/workflows/get-mhy-wish.yml"
          - files~=^script/mihoyo
          - files="script/miyoushe.py"
          - files="script/hoyolab.py"  
        - check-success=py-game-wish  
      - and:
        - or:
          - files="script/requirements.txt"
          - files=".github/workflows/life-recent-update.yml"
          - files~=^life/
        - check-success=py-life-recent
    actions:
      merge:
        method: merge

  # - name: automatic merge for python script latest life
  #   conditions:
  #     - author=DrAugus
  #     - "title=docs: life latest"
  #     - -check-failure~=^deploy-
  #     - -check-failure~=^py-
  #   actions:
  #     merge:
  #       method: merge

  # - name: automatic merge for auto get mhy wish
  #   conditions:
  #     - author=DrAugus
  #     - "title=feat: auto get mhy wish"
  #     - check-success~=^deploy-
  #     - -check-failure~=^py-
  #   actions:
  #     merge:
  #       method: merge

  - name: automatic merge for dev-game/py
    conditions:
      - author=DrAugus
      - or:
        - head=dev-game
        - head=dev-py
      # PR is not a draft
      - -draft
      - not:
          or:
            - check-failure=deploy-life (ubuntu-latest, 16, life/.vitepress/dist, augusmeow, life)
            - check-failure=deploy-life (ubuntu-latest, 16, life/.vitepress/dist, augusmeow, augusmeow.github.io)
            - check-failure=deploy-game (ubuntu-latest, 16, game/.vitepress/dist, augusmeow, game)
            - check-failure=py-game-wish
            - check-failure=py-life-recent
    actions:
      merge:
        method: merge

  # https://docs.mergify.com/workflow/delete-head-branches/#prevent-deletion-for-dependent-branches
  - name: delete head branch after merge but not if other PRs depend on it
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
