pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success~=^deploy-
      - files!=requirements.txt
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success~=^deploy-
      - files!=requirements.txt
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - check-success~=^deploy-
      - files!=requirements.txt
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot pull requests py
    conditions:
      - author=dependabot[bot]
      - check-success~=^py-
      - files=requirements.txt
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests py
    conditions:
      - author=renovate[bot]
      - check-success~=^py-
      - files=requirements.txt
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests py
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - check-success~=^py-
      - files=requirements.txt
    actions:
      merge:
        method: merge

  # - name: automatic merge for python script latest life
  #   conditions:
  #     - author=DrAugus
  #     - "title=docs: life latest"
  #     - -check-failure~=^deploy-
  #     - -check-failure~=^py-
  #   actions:
  #     merge:
  #       method: merge

  # - name: automatic merge for auto get mhy wish
  #   conditions:
  #     - author=DrAugus
  #     - "title=feat: auto get mhy wish"
  #     - check-success~=^deploy-
  #     - -check-failure~=^py-
  #   actions:
  #     merge:
  #       method: merge

  - name: automatic merge for dev-game
    conditions:
      - author=DrAugus
      - -check-failure~=^deploy-
      - -check-failure~=^py-
      - head=dev-game
    actions:
      merge:
        method: merge

  - name: automatic merge for dev-py
    conditions:
      - author=DrAugus
      - -check-failure~=^deploy-
      - -check-failure~=^py-
      - head=dev-py
    actions:
      merge:
        method: merge        

  # https://docs.mergify.com/workflow/delete-head-branches/#prevent-deletion-for-dependent-branches
  - name: delete head branch after merge but not if other PRs depend on it
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
