pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot pull requests
    conditions:
      - author=dependabot[bot]
      # condition
      # https://docs.mergify.com/conditions/#github-actions
      - not: check-failure=deploy-game
      - not: check-failure=deploy-art
      - not: check-failure=deploy-code
      - not: check-failure=deploy-notes
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - not: check-failure=deploy-game
      - not: check-failure=deploy-art
      - not: check-failure=deploy-code
      - not: check-failure=deploy-notes
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - not: check-failure=deploy-game
      - not: check-failure=deploy-art
      - not: check-failure=deploy-code
      - not: check-failure=deploy-notes
    actions:
      merge:
        method: merge

  # - name: automatic merge for auto pull requests
  #   conditions:
  #     - title=pulling refs/heads/dev into master
  #   actions:
  #     merge:
  #       method: merge
