pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
    actions:
      merge:
        method: merge

  - name: automatic merge for dependabot pull requests
    conditions:
      - author=dependabot[bot]
      # 这三个不一定全都会响应 在此判定 任意一个失败都不可以
      - not:
          or:
            - check-failure=deploy
            - check-failure=Vercel – art
            - check-failure=Vercel – docus
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - not:
          or:
            - check-failure=deploy
            - check-failure=Vercel – art
            - check-failure=Vercel – docus
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - not:
          or:
            - check-failure=deploy
            - check-failure=Vercel – art
            - check-failure=Vercel – docus
    actions:
      merge:
        method: merge

  # - name: automatic merge for auto pull requests
  #   conditions:
  #     - title=pulling refs/heads/dev into master
  #     - not:
  #         or:
  #           - check-failure=deploy
  #           - check-failure=Vercel – art
  #           - check-failure=Vercel – docus
  #   actions:
  #     merge:
  #       method: merge