pull_request_rules:
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - check-success=Summary
      - check-success=restyled
    actions:
      merge:
        method: merge

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=Summary
      - check-success=restyled
    actions:
      merge:
        method: merge

  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - check-success=Summary
      - check-success=restyled
    actions:
      merge:
        method: merge

  - name: automatic merge for restyled-io pull requests
    conditions:
      - author=restyled-io[bot]
      - check-success=Summary
      - check-success=restyled
    actions:
      merge:
        method: merge

  - name: automatic merge for auto pull requests
    conditions:
      - title=pulling refs/heads/dev into master
      - check-success=Open PR to master
      - check-success=deploy
      - check-success=CodeFactor
      - check-success=CommitCheck
      - check-success=Summary
      - check-success=restyled
    actions:
      merge:
        method: merge