name: Staging Auto-PR
on:
  push:
    branches:
      - dev-game

jobs:
  pull-request:
    name: Open PR to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: master
          pr_title: "pulling ${{ github.ref }} into master"
          pr_body: "👑 *An automated PR* for game"
          github_token: ${{ secrets.DEPLOY_GH }}
