name: ci-codecov

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  codecov:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./art

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
