name: ci-deploy-docus

on:
  push:
    branches:
      - master
    paths:
      - 'nuxt-docus/**'      
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - 'nuxt-docus/**' 

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]

    runs-on: ${{ matrix.os }}

    defaults:
          run:
            working-directory: ./nuxt-docus

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          repo: DrAugus/site-nuxt-docus
          target_branch: gh-pages
          build_dir: nuxt-docus/dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}