name: ci-deploy-arts

on:
  push:
    branches:
      - master
    paths:
      - "arts/**"
      - ".github/workflows/deploy-arts.yml"
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - "arts/**"

jobs:
  deploy-arts:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]
        deploy-dir: [arts/.vitepress/dist]
        deploy-user: [augusmeow]
        deploy-repo: [arts]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./arts

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      # 运行构建脚本
      - name: Build VitePress site
        env:
          BASE: /arts/
          HOSTNAME: https://augusmeow.github.io/arts/
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          repo: ${{ matrix.deploy-user }}/${{ matrix.deploy-repo }}
          target_branch: gh-pages
          build_dir: ${{ matrix.deploy-dir }}
          jekyll: false
        env:
          GH_PAT: ${{ secrets.DEPLOY_GH }}
