name: ci-deploy-code

on:
  push:
    branches:
      - master
    paths:
      - "code/**"
      - ".github/workflows/deploy-site-code.yml"
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - "code/**"

jobs:
  deploy-code:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]
        deploy-dir: [code/.output/public]
        deploy-user: [augusmeow]
        deploy-repo: [code]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./code

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Generate
        env:
          BASE: /${{ matrix.deploy-repo }}/
          HOSTNAME: https://draugus.github.io/
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm generate

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          repo: ${{ matrix.deploy-user }}/${{ matrix.deploy-repo }}
          target_branch: gh-pages
          build_dir: ${{ matrix.deploy-dir }}
          jekyll: false
        env:
          GH_PAT: ${{ secrets.DEPLOY_GH }}
