name: ci-deploy-game

on:
  # make sure this is the branch you are using
  push:
    branches:
      - master
    paths:
      - "game/**"
      - ".github/workflows/deploy-site-game.yml"
  # 手动触发部署
  # workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - "game/**"
      - ".github/workflows/deploy-site-game.yml"

jobs:
  deploy-game:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [16]
        deploy-dir: [game/src/.vuepress/dist]
        deploy-user: [augusmeow]
        deploy-repo: [game]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./game

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: ${{ matrix.node }}
          cache: yarn

      # 安装依赖
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 运行构建脚本
      - name: Build VuePress site
        env:
          BASE: /
          HOSTNAME: https://draugus.github.io/
          NODE_OPTIONS: --max_old_space_size=4096
        run: yarn run augus:build

      # 防止加载不到 _开头的文件 下面已经有了
      # @see https://github.com/orgs/github-community/discussions/19794
      # - name: Add nojekyll
      #   run: |
      #     cd src/.vuepress/dist
      #     touch .nojekyll

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
       # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          repo: ${{ matrix.deploy-user }}/${{ matrix.deploy-repo }}
          target_branch: gh-pages
          build_dir: ${{ matrix.deploy-dir }}
          jekyll: false
        env:
          GH_PAT: ${{ secrets.DEPLOY_GH }}
