name: Life recent script workflow
on:  
  push:
    branches:
      - master
    paths:
      - "life/**"
      - "!life/.vitepress/**"
      - "!life/*"
      - ".github/workflows/life-recent-update.yml"
    # paths-ignore:
    #   - "life/.vitepress/**"
  schedule:
    # This is run at UTC 16:00 p.m., aka UTC+8 0:00 a.m.
    - cron:  '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./script
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Python script
      run: |
        python latest.py    
        git log --since="7 days ago" --pretty=format:"" --name-only --diff-filter=AMR | sort | uniq
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "docs: life latest" -a
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.DEPLOY_GH }}
    #     branch: ${{ github.head_ref }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.DEPLOY_GH }}
        title: "docs: life latest"
        commit-message: "docs: life latest"
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        branch: create-pull-request/patch-life-recent-update
        base: master    
        labels: |
          report
          automated pr
        assignees: DrAugus
        # Review cannot be requested from pull request author.
        # reviewers: DrAugus  